name: "CI - Static Checks"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  code-style-check:
    name: Code Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run prek
        uses: j178/prek-action@v1

  type-check:
    runs-on: ubuntu-latest
    name: Type Check
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"

      - name: Type check
        run: |
          uv sync --group dev
          uvx ty check src/
